title: Bibliai tanulmányok
description: Orosz Sándor Ádám írásai
theme: jekyll-theme-cayman
paginate: false
url: "https://oroszsandoradam.github.io"
author: "Orosz Sándor Ádám"
lang: hu-HU
plugins:
  - jekyll-seo-tag
